--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: review_reactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review_reactions (
    id bigint NOT NULL,
    client_id bigint,
    liked boolean,
    review_id bigint
);


ALTER TABLE public.review_reactions OWNER TO postgres;

--
-- Name: review_reactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    client_id bigint,
    comment character varying(255),
    dislike_count integer,
    like_count integer,
    order_id bigint,
    product_id bigint,
    rating integer NOT NULL,
    review_date timestamp(6) without time zone
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: review_reactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.review_reactions (id, client_id, liked, review_id) FROM stdin;
5	4	t	1
7	4	t	4
8	3991	t	11
9	3991	t	6
10	3991	f	13
11	3991	t	17
12	3991	f	12
13	3991	t	9
14	3991	f	18
18	4	t	20
19	4	t	21
20	4	t	22
17	4	t	19
21	4	t	11
22	4	f	17
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reviews (id, client_id, comment, dislike_count, like_count, order_id, product_id, rating, review_date) FROM stdin;
1	4	Ok	0	1	1186	3	3	2025-08-24 00:10:29.461
2	4	I like it	\N	\N	1185	252	4	2025-09-03 14:05:08.217
3	4	Very nice	\N	\N	1192	228	5	2025-09-03 22:46:40.898
4	4	Very Nice I lile it!!!	\N	2	1216	12	4	2025-09-08 17:45:02.566
5	3991	I like it very much!	\N	\N	1223	228	4	2025-09-09 11:25:10.584
7	3991	super nice	\N	\N	1223	228	4	2025-09-09 11:25:33.876
8	3991	i likeeee	\N	\N	1223	67	3	2025-09-09 11:25:41.834
10	3991	Nu imi place	\N	\N	1223	67	1	2025-09-09 11:25:53.44
14	3991	imi place mult mult	\N	\N	1224	252	4	2025-09-09 11:32:08.988
15	3991	este ok 	\N	\N	1224	105	4	2025-09-09 11:32:14.807
16	3991	tare	\N	\N	1224	298	5	2025-09-09 11:32:18.986
6	3991	Imi place mult	\N	1	1223	19	5	2025-09-09 11:25:25.226
13	3991	imi place multtt	1	\N	1224	18	4	2025-09-09 11:31:57.205
12	3991	cel mai bun	1	\N	1224	20	4	2025-09-09 11:31:49.234
9	3991	Nice nice	\N	1	1223	88	5	2025-09-09 11:25:48.474
18	3991	Cea mai frumoasa	1	\N	1223	88	5	2025-09-09 11:32:38.839
20	4	frumos, folositor	\N	1	1194	290	3	2025-09-09 13:00:47.037
21	4	veri niceee	\N	1	1225	233	5	2025-09-11 00:45:59.864
22	4		\N	1	1226	18	4	2025-09-11 10:17:10.435
19	3991	Niceee	0	1	1224	21	4	2025-09-09 11:39:37.22
11	3991	bestttt	\N	2	1224	21	5	2025-09-09 11:31:44.062
17	3991	niceeee	1	0	1224	22	5	2025-09-09 11:32:30.223
23	4	Niceee	\N	\N	1227	12	3	2025-10-18 17:26:38.085
\.


--
-- Name: review_reactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.review_reactions_id_seq', 22, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reviews_id_seq', 23, true);


--
-- Name: review_reactions review_reactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review_reactions
    ADD CONSTRAINT review_reactions_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

